# Generated by Django 3.1.5 on 2021-01-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userclickstat',
            old_name='urlcreatedby',
            new_name='url_created_by',
        ),
    ]
